### ISSUE TITLE
Unable to load level, panics at Some(Visit(RegionDoesNotExist("NormalTexture")))

### ISSUE THREAD

**Issue by garak92** [FyroxEngine/Fyrox-tutorials#5]
Hello. I was following the tutorial here https://rg3d.rs/tutorials/2021/03/05/tutorial1.html but when I try to load the scene, I get this error. Here is the complete log. 

The system is: 

* Linux 5.14.2-arch1-2 x86_64 GNU/Linux
* Arch Linux x86_64

Update: it works with your scene (if I do a git clone of this repo) but not with scenes made by me on the editor compiled on my own system.

Update 2: the problem seems to be the editor or some configuration of it. When I open your scenes and save them on my version of the editor, I get the same error. Btw, the textures do not load. I guess it is related to the fact that the textures folder is not asked for.

It may be useful (or maybe not, but just in case) to point out that the editor asks for my working directory (which I defined as the src of my project) but not the textures folder as shown on the tutorial.

Thanks in advance.

[INFO]: Shader FlatShader_VertexShader compiled!

[INFO]: Shader FlatShader_FragmentShader compiled!

[INFO]: Shader FlatShader linked!

[INFO]: Shader SsaoShader_VertexShader compiled!

[INFO]: Shader SsaoShader_FragmentShader compiled!

[INFO]: Shader SsaoShader linked!

[INFO]: Shader DeferredLightShader_VertexShader compiled!

[INFO]: Shader DeferredLightShader_FragmentShader compiled!

[INFO]: Shader DeferredLightShader linked!

[INFO]: Shader DeferredLightShader_VertexShader compiled!

[INFO]: Shader DeferredLightShader_FragmentShader compiled!

[INFO]: Shader DeferredLightShader linked!

[INFO]: Shader DeferredLightShader_VertexShader compiled!

[INFO]: Shader DeferredLightShader_FragmentShader compiled!

[INFO]: Shader DeferredLightShader linked!

[INFO]: Shader AmbientLightShader_VertexShader compiled!

[INFO]: Shader AmbientLightShader_FragmentShader compiled!

[INFO]: Shader AmbientLightShader linked!

[INFO]: Shader FlatShader_VertexShader compiled!

[INFO]: Shader FlatShader_FragmentShader compiled!

[INFO]: Shader FlatShader linked!

[INFO]: Shader SpotShadowMapShader_VertexShader compiled!

[INFO]: Shader SpotShadowMapShader_FragmentShader compiled!

[INFO]: Shader SpotShadowMapShader linked!

[INFO]: Shader PointShadowMapShader_VertexShader compiled!

[INFO]: Shader PointShadowMapShader_FragmentShader compiled!

[INFO]: Shader PointShadowMapShader linked!

[INFO]: Shader SpotVolumetricLight_VertexShader compiled!

[INFO]: Shader SpotVolumetricLight_FragmentShader compiled!

[INFO]: Shader SpotVolumetricLight linked!

[INFO]: Shader PointVolumetricLight_VertexShader compiled!

[INFO]: Shader PointVolumetricLight_FragmentShader compiled!

[INFO]: Shader PointVolumetricLight linked!

[INFO]: Shader FlatShader_VertexShader compiled!

[INFO]: Shader FlatShader_FragmentShader compiled!

[INFO]: Shader FlatShader linked!

[INFO]: Shader FlatShader_VertexShader compiled!

[INFO]: Shader FlatShader_FragmentShader compiled!

[INFO]: Shader FlatShader linked!

[INFO]: Shader FlatShader_VertexShader compiled!

[INFO]: Shader FlatShader_FragmentShader compiled!

[INFO]: Shader FlatShader linked!

[INFO]: Shader UIShader_VertexShader compiled!

[INFO]: Shader UIShader_FragmentShader compiled!

[INFO]: Shader UIShader linked!

[INFO]: Shader ParticleSystemShader_VertexShader compiled!

[INFO]: Shader ParticleSystemShader_FragmentShader compiled!

[INFO]: Shader ParticleSystemShader linked!

[INFO]: Shader DebugShader_VertexShader compiled!

[INFO]: Shader DebugShader_FragmentShader compiled!

[INFO]: Shader DebugShader linked!

[INFO]: Shader ForwardShader_VertexShader compiled!

[INFO]: Shader ForwardShader_FragmentShader compiled!

[INFO]: Shader ForwardShader linked!

[INFO]: Shader FXAAShader_VertexShader compiled!

[INFO]: Shader FXAAShader_FragmentShader compiled!

[INFO]: Shader FXAAShader linked!

[INFO]: Shader SpriteShader2D_VertexShader compiled!

[INFO]: Shader SpriteShader2D_FragmentShader compiled!

[INFO]: Shader SpriteShader2D linked!

[ERROR]: Unable to load model from "data/models/scene.rgs"! Reason Visit(RegionDoesNotExist("NormalTexture"))

**Comment by mrDIMAS** [comment]
Hi, it happens because the editor uses latest rg3d and data format of scenes changes between engine versions, in most cases there is backward compatibility between adjacent versions, but in some cases it is impossible. I'm pretty sure that in your case you're using 0.20(?) rg3d with the editor built with 0.23+. The 0.23 has new material system and there is no full backward compatibility between them, this means that terrains (and probably something else) are not backward compatible, but everything else should be. The scene has a terrain in it, so it is not compatible with 0.23+. 

This is acceptable situation since the engine has not reached 1.0.0 version yet, the data format will stabilize only at 1.0.0.

**Comment by mrDIMAS** [comment]
Already fixed.
