### ISSUE TITLE
Canvas and Text

### ISSUE THREAD

**Issue by bocksdin** [FyroxEngine/Fyrox-tutorials#8]
I don't see a way to create a canvas and/or text (or other UI elements) within the FyroxEd. They also don't appear to be created via code using the snippets in the documentation. Are they currently implemented and expected to be working? If so, could you please provide a full example of it working?

Edit: Here is my code. The UI pieces are in the `score` script. https://github.com/RoryLetteney/crab-clicker/tree/main/game/src

Edit2: Looks like text may only show up when inside something like a border or button?

**Comment by mrDIMAS** [comment]
Hi, FyroxEd does not have a UI editor yet. You need to create UI via code in your game. It is planned, but I don't know when I have time to implement it. 

Also, this https://github.com/RoryLetteney/crab-clicker/blob/main/game/src/lib.rs#L73 will always be false if you run the game outside of the editor. You need to move this piece of code here https://github.com/RoryLetteney/crab-clicker/blob/main/game/src/lib.rs#L153. That may be the cause why you don't see the text/
